In [1]:
import pandas as pd
import sklearn
import numpy as np

In [2]:
rate = pd.read_csv("train.csv")

In [3]:
rate.head()

Income  LoanAmountRequest  CreditScore  NoofDefaults  PropertyPrice  \
0  1933.05           72809.58       809.44             0      119933.46   
1  4952.91           46837.47       780.40             0       54791.00   
2   988.19           45593.04       833.15             0       72440.58   
3  1933.05           80057.92       832.70             1      121441.51   
4  2614.77          113858.89       745.55             1      208567.91   

      CLA  PropertyType  PropertyAge       LSA  
0  241.08             4      1933.05  54607.18  
1  495.81             2      4952.91  37469.98  
2  171.95             2       988.19  36474.43  
3  298.54             2      2614.77  56040.54  
4  491.41             4      2614.77  74008.28

In [4]:
rate.shape

(30000, 9)

In [5]:
rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Income             30000 non-null  float64
 1   LoanAmountRequest  30000 non-null  float64
 2   CreditScore        30000 non-null  float64
 3   NoofDefaults       30000 non-null  int64  
 4   PropertyPrice      30000 non-null  float64
 5   CLA                30000 non-null  float64
 6   PropertyType       30000 non-null  int64  
 7   PropertyAge        30000 non-null  float64
 8   LSA                30000 non-null  float64
dtypes: float64(7), int64(2)
memory usage: 2.1 MB


In [6]:
rate.dropna()

Income  LoanAmountRequest  CreditScore  NoofDefaults  PropertyPrice  \
0      1933.05           72809.58       809.44             0      119933.46   
1      4952.91           46837.47       780.40             0       54791.00   
2       988.19           45593.04       833.15             0       72440.58   
3      1933.05           80057.92       832.70             1      121441.51   
4      2614.77          113858.89       745.55             1      208567.91   
...        ...                ...          ...           ...            ...   
29995  4969.41           76657.90       869.61             0      111096.56   
29996  1606.88           66595.14       729.41             0       73453.94   
29997  2250.19           81410.08       780.29             0      102108.02   
29998  2417.71          142524.10       677.27             1      168194.47   
29999  3068.24          156290.54       815.44             0      194512.60   

          CLA  PropertyType  PropertyAge        LSA  
0      241.08             4      1933.05   54607.18  
1      495.81             2      4952.91   37469.98  
2      171.95             2       988.19   36474.43  
3      298.54             2      2614.77   56040.54  
4      491.41             4      2614.77   74008.28  
...       ...           ...          ...        ...  
29995  722.34             4      4969.41   68992.11  
29996  253.04             3      1606.88   46616.60  
29997  583.11             1      2417.71   61057.56  
29998  378.29             4      2417.71   99766.87  
29999  693.94             3      3068.24  117217.90  

[30000 rows x 9 columns]

In [7]:
rate.fillna(0)

Income  LoanAmountRequest  CreditScore  NoofDefaults  PropertyPrice  \
0      1933.05           72809.58       809.44             0      119933.46   
1      4952.91           46837.47       780.40             0       54791.00   
2       988.19           45593.04       833.15             0       72440.58   
3      1933.05           80057.92       832.70             1      121441.51   
4      2614.77          113858.89       745.55             1      208567.91   
...        ...                ...          ...           ...            ...   
29995  4969.41           76657.90       869.61             0      111096.56   
29996  1606.88           66595.14       729.41             0       73453.94   
29997  2250.19           81410.08       780.29             0      102108.02   
29998  2417.71          142524.10       677.27             1      168194.47   
29999  3068.24          156290.54       815.44             0      194512.60   

          CLA  PropertyType  PropertyAge        LSA  
0      241.08             4      1933.05   54607.18  
1      495.81             2      4952.91   37469.98  
2      171.95             2       988.19   36474.43  
3      298.54             2      2614.77   56040.54  
4      491.41             4      2614.77   74008.28  
...       ...           ...          ...        ...  
29995  722.34             4      4969.41   68992.11  
29996  253.04             3      1606.88   46616.60  
29997  583.11             1      2417.71   61057.56  
29998  378.29             4      2417.71   99766.87  
29999  693.94             3      3068.24  117217.90  

[30000 rows x 9 columns]

In [8]:
rate.isnull().sum()

Income               0
LoanAmountRequest    0
CreditScore          0
NoofDefaults         0
PropertyPrice        0
CLA                  0
PropertyType         0
PropertyAge          0
LSA                  0
dtype: int64

In [9]:
rate.shape


(30000, 9)

In [10]:
X= rate.drop(columns='LSA')
y= rate['LSA']

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2)

In [12]:

from sklearn.linear_model import LinearRegression
##from sklearn.tree import DecisionTreeRegressor
##from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [13]:
ohe = OneHotEncoder()
ohe.fit(X[['Income',	'LoanAmountRequest',	'CreditScore',	'NoofDefaults',	'PropertyPrice',	'CLA',	'PropertyType',	'PropertyAge'
]])

OneHotEncoder()

In [14]:
ohe.categories_

[array([3.77700000e+02, 3.78760000e+02, 3.78910000e+02, ...,
        5.46537500e+04, 1.22966280e+05, 1.77746021e+06]),
 array([  6048.24,   6108.05,   6145.01, ..., 564812.49, 602384.15,
        621497.82]),
 array([580.  , 580.85, 581.66, ..., 891.95, 892.18, 896.26]),
 array([0, 1], dtype=int64),
 array([-9.99000000e+02,  7.26595000e+03,  7.30987000e+03, ...,
         9.87770870e+05,  1.02808264e+06,  1.07796673e+06]),
 array([-999.  ,   33.76,   34.04, ..., 3025.4 , 3419.66, 3840.88]),
 array([1, 2, 3, 4], dtype=int64),
 array([3.77700000e+02, 3.78760000e+02, 3.78910000e+02, ...,
        5.46537500e+04, 1.22966280e+05, 1.77746021e+06])]

In [15]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['Income',	'LoanAmountRequest',	'CreditScore',	'NoofDefaults',	'PropertyPrice',	'CLA',	'PropertyType',	'PropertyAge'	]),remainder= 'passthrough')

In [16]:
lr=LinearRegression()

In [17]:
pipe = make_pipeline(column_trans,lr)

In [18]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array([3.77700000e+02, 3.78760000e+02, 3.78910000e+02, ...,
       5.46537500e+04, 1.22966280e+05, 1.77746021e+06]),
                                                                            array([  6048.24,   6108.05,   6145.01, ..., 564812.49, 602384.15,
       621497.82]),
                                                                            array([580.  , 580.85, 581.66, ..., 891.95, 892.18,...
        9.87770870e+05,  1.02808264e+06,  1.07796673e+06]),
                                                                            array([-999.  ,   33.76,   34.04, ..., 3025.4 , 3419.66, 3840.88]),
                                                                            array([1, 2, 3, 4], dtype=int64),
                                                                            array([3.77700000e+02, 3.78760000e+02, 3.78910000e+02, ...,
       5.46537500e+04, 1.22966280e+05, 1.77746021e+06])]),
                                                  ['Income',
                                                   'LoanAmountRequest',
                                                   'CreditScore',
                                                   'NoofDefaults',
                                                   'PropertyPrice', 'CLA',
                                                   'PropertyType',
                                                   'PropertyAge'])])),
                ('linearregression', LinearRegression())])

In [19]:
y_pred= pipe.predict(X_test)

In [20]:
r2_score(y_test,y_pred)

-0.0011857835098403324

In [21]:
scores=[]
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))

In [22]:
np.argmax(scores)

5

In [23]:
scores[np.argmax(scores)]

0.0055822646456547

In [24]:
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=np.argmax(scores))
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    r2_score(y_test,y_pred)

0.0055822646456547

In [25]:
from sklearn.metrics import r2_score , mean_squared_error
r2_score(y_test,y_pred)

0.0055822646456547

In [26]:
mean_squared_error(y_test, y_pred)

2393730121.9982853

In [27]:
from sklearn.model_selection import cross_val_score
cross_val_score(lr, X_train, y_train, cv=10)

array([0.57878282, 0.5642596 , 0.52656957, 0.5919705 , 0.59625963,
       0.5131004 , 0.57326935, 0.55779968, 0.56162184, 0.59985077])

In [28]:
import pickle

In [29]:
pickle.dump(pipe,open('AmountPrediction.pkl','wb'))

In [30]:
pipe.predict(pd.DataFrame([[1933.05,	72809.58,	809.44,	0,	119933.46,	241.08,	4,	1933.05
]], columns=	['Income',	'LoanAmountRequest',	'CreditScore',	'NoofDefaults',	'PropertyPrice',	'CLA',	'PropertyType',	'PropertyAge']))

array([54605.4035331])