In [1]:
import pandas as pd
import sklearn
import numpy as np

In [2]:
rate = pd.read_csv("data.csv")

In [3]:
rate.head()

CashReserveRatio  CashDepositRatio  ReverseRepoRate  MarginalFacilityRate  \
0               4.0              0.00              4.9                   5.4   
1               4.0              4.71              4.9                   5.4   
2               4.0              0.00              4.9                   5.4   
3               4.0              4.95              4.9                   5.4   
4               4.0              0.00              4.9                   5.4   

   BankRate  TermDepositRate  SavingsDepositRate  CallMoneyRate  TreasuryBill  \
0       5.4              6.1                3.25           4.92          5.21   
1       5.4              6.1                3.25           5.05          5.22   
2       5.4              6.1                3.25           5.11          5.22   
3       5.4              6.1                3.25           5.06          5.19   
4       5.4              6.2                3.25           4.98          5.19   

   Inflation  RepoRate  BaseRate  
0       6.62      5.15      8.45  
1       6.62      5.15      8.45  
2       3.73      5.15      8.45  
3       3.73      5.15      8.45  
4       3.73      5.15      8.45

In [4]:
rate.shape

(1343, 12)

In [5]:
rate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1343 entries, 0 to 1342
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   CashReserveRatio      1343 non-null   float64
 1   CashDepositRatio      1343 non-null   float64
 2   ReverseRepoRate       1343 non-null   float64
 3   MarginalFacilityRate  1343 non-null   float64
 4   BankRate              1343 non-null   float64
 5   TermDepositRate       1343 non-null   float64
 6   SavingsDepositRate    1343 non-null   float64
 7   CallMoneyRate         1343 non-null   float64
 8   TreasuryBill          1343 non-null   float64
 9   Inflation             1343 non-null   float64
 10  RepoRate              1343 non-null   float64
 11  BaseRate              1343 non-null   float64
dtypes: float64(12)
memory usage: 126.0 KB


In [6]:
X= rate.drop(columns='BaseRate')
y= rate['BaseRate']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2)

In [8]:
##from sklearn.linear_model import LinearRegression
##from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [9]:
ohe = OneHotEncoder()
ohe.fit(X[['CashReserveRatio','CashDepositRatio','MarginalFacilityRate','TermDepositRate','CallMoneyRate','TreasuryBill','ReverseRepoRate','BankRate', 'SavingsDepositRate','Inflation', 'RepoRate']])

OneHotEncoder()

In [10]:
ohe.categories_

[array([0.  , 4.  , 4.23, 4.25, 4.47, 4.5 , 4.54, 4.55, 4.57, 4.58, 4.6 ,
        4.61, 4.62, 4.63, 4.64, 4.65, 4.66, 4.67, 4.68, 4.69, 4.7 , 4.71,
        4.72, 4.73, 4.74, 4.75, 4.76, 4.77, 4.78, 4.79, 4.8 , 4.81, 4.82,
        4.83, 4.84, 4.85, 4.87, 4.88, 4.89, 4.9 , 4.92, 4.94, 4.95, 4.96,
        4.97, 5.02, 5.04, 5.07, 5.09, 5.1 , 5.11, 5.12, 5.14, 5.15, 5.16,
        5.17, 5.19, 5.22, 5.23, 5.24, 5.26, 5.27, 5.28, 5.3 , 5.4 , 5.41,
        5.44, 5.46, 5.5 , 5.52, 5.63, 5.68, 5.7 , 5.71, 5.72, 5.75, 5.76,
        5.78, 5.79, 5.82, 5.88, 5.9 , 5.99, 6.  , 6.08, 6.2 , 6.25, 6.34,
        6.5 , 6.53, 6.66, 6.73, 6.75, 6.78, 6.82, 7.  , 7.02, 7.25, 7.5 ,
        9.03]),
 array([ 0.  ,  4.  ,  4.23,  4.25,  4.47,  4.5 ,  4.54,  4.55,  4.57,
         4.58,  4.6 ,  4.61,  4.62,  4.63,  4.64,  4.65,  4.66,  4.67,
         4.68,  4.69,  4.7 ,  4.71,  4.72,  4.73,  4.74,  4.75,  4.76,
         4.77,  4.78,  4.79,  4.8 ,  4.81,  4.82,  4.83,  4.84,  4.85,
         4.87,  4.88,  4.89,  4.9 

In [11]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['CashReserveRatio','CashDepositRatio','MarginalFacilityRate','TermDepositRate','CallMoneyRate','TreasuryBill','ReverseRepoRate','BankRate', 'SavingsDepositRate','Inflation', 'RepoRate']),remainder= 'passthrough')

In [12]:
lr=RandomForestRegressor()

In [13]:
pipe = make_pipeline(column_trans,lr)

In [14]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array([0.  , 4.  , 4.23, 4.25, 4.47, 4.5 , 4.54, 4.55, 4.57, 4.58, 4.6 ,
       4.61, 4.62, 4.63, 4.64, 4.65, 4.66, 4.67, 4.68, 4.69, 4.7 , 4.71,
       4.72, 4.73, 4.74, 4.75, 4.76, 4.77, 4.78, 4.79, 4.8 , 4.81, 4.82,
       4.83, 4.84, 4.85, 4.87, 4.88, 4.89, 4.9 , 4.92, 4.94, 4.95, 4...
        9.13,  9.14,  9.15,  9.16,  9.18,  9.19,  9.22,  9.23,  9.27,
        9.3 ,  9.34,  9.36,  9.44,  9.45,  9.46,  9.71,  9.81,  9.9 ,
        9.91,  9.93, 10.1 , 10.18, 10.21, 10.23, 10.29, 10.38])]),
                                                  ['CashReserveRatio',
                                                   'CashDepositRatio',
                                                   'MarginalFacilityRate',
                                                   'TermDepositRate',
                                                   'CallMoneyRate',
                                                   'TreasuryBill',
                                                   'ReverseRepoRate',
                                                   'BankRate',
                                                   'SavingsDepositRate',
                                                   'Inflation',
                                                   'RepoRate'])])),
                ('randomforestregressor', RandomForestRegressor())])

In [15]:
y_pred= pipe.predict(X_test)

In [16]:
r2_score(y_test,y_pred)

0.8912667070434498

In [17]:
scores=[]
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=i)
    lr=RandomForestRegressor()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))

In [18]:
np.argmax(scores)

4

In [19]:
scores[np.argmax(scores)]

0.8968700050376085

In [20]:
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=np.argmax(scores))
    lr=RandomForestRegressor()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    r2_score(y_test,y_pred)

0.8996094147061606

In [21]:
from sklearn.metrics import r2_score , mean_squared_error
r2_score(y_test,y_pred)

0.8996094147061606

In [22]:
mean_squared_error(y_test, y_pred)

0.33905368381867

In [23]:
from sklearn.model_selection import cross_val_score
cross_val_score(lr, X_train, y_train, cv=10)

array([0.92055783, 0.89370632, 0.95127139, 0.96638837, 0.9767228 ,
       0.93138265, 0.95673978, 0.73010474, 0.77466662, 0.86954474])

In [24]:
import pickle

In [25]:
pickle.dump(pipe,open('RandomForestRegressorModel.pkl','wb'))

In [26]:
pipe.predict(pd.DataFrame([[4, 0,	4.9,	5.4,	5.4,	6.1,	3.25,	4.92,	5.21,	6.62,	5.15

]], columns=	['CashReserveRatio',	'CashDepositRatio',	'ReverseRepoRate',	'MarginalFacilityRate',	'BankRate', 	
           'TermDepositRate',	'SavingsDepositRate',	'CallMoneyRate',	'TreasuryBill',	'Inflation',	'RepoRate']))

array([8.5231])